
import React from "react";
import { Link } from "react-router-dom";
import Layout from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { FileText, Layout as LayoutIcon, Pencil } from "lucide-react";

const Examples = () => {
  return (
    <Layout>
      <div className="bg-gradient-to-br from-tekk-soft-purple to-white py-12">
        <div className="container mx-auto px-4 text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">See What Tekk.ai Can Do</h1>
          <p className="text-lg text-gray-700 mb-8 max-w-2xl mx-auto">
            Explore examples of PRDs, FRDs, and mockups generated by our platform for various industries and use cases.
          </p>
        </div>
      </div>

      <section className="py-12 bg-white">
        <div className="container mx-auto px-4">
          <Tabs defaultValue="prd" className="w-full max-w-4xl mx-auto">
            <TabsList className="grid w-full grid-cols-3 mb-8">
              <TabsTrigger value="prd" className="flex items-center gap-2">
                <FileText className="h-4 w-4" />
                <span>PRD Examples</span>
              </TabsTrigger>
              <TabsTrigger value="frd" className="flex items-center gap-2">
                <LayoutIcon className="h-4 w-4" />
                <span>FRD Examples</span>
              </TabsTrigger>
              <TabsTrigger value="mockup" className="flex items-center gap-2">
                <Pencil className="h-4 w-4" />
                <span>Mockup Examples</span>
              </TabsTrigger>
            </TabsList>
            
            {/* PRD Examples */}
            <TabsContent value="prd" className="mt-2">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <ExampleCard 
                  title="E-commerce Mobile App"
                  category="Retail"
                  description="A comprehensive PRD for a feature-rich e-commerce mobile application targeting fashion retailers."
                  documentType="prd"
                />
                <ExampleCard 
                  title="Healthcare Patient Portal"
                  category="Healthcare"
                  description="A detailed PRD for a patient portal allowing appointment scheduling, health record access, and doctor communication."
                  documentType="prd"
                />
                <ExampleCard 
                  title="Project Management Tool"
                  category="Productivity"
                  description="A thorough PRD outlining features for a project management platform designed for remote teams."
                  documentType="prd"
                />
                <ExampleCard 
                  title="Smart Home Controller"
                  category="IoT"
                  description="A complete PRD for a central smart home controller app to manage all connected devices."
                  documentType="prd"
                />
              </div>
            </TabsContent>
            
            {/* FRD Examples */}
            <TabsContent value="frd" className="mt-2">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <ExampleCard 
                  title="Financial Dashboard"
                  category="Finance"
                  description="An FRD detailing the technical requirements and architecture for a real-time financial analytics dashboard."
                  documentType="frd"
                />
                <ExampleCard 
                  title="Video Streaming Platform"
                  category="Entertainment"
                  description="A technical FRD covering the backend architecture and API specifications for a video streaming service."
                  documentType="frd"
                />
                <ExampleCard 
                  title="CRM Integration"
                  category="Business"
                  description="An FRD specifying the integration points, data models, and workflows for a CRM system connecting with multiple platforms."
                  documentType="frd"
                />
                <ExampleCard 
                  title="Logistics Tracking System"
                  category="Supply Chain"
                  description="A functional requirements document outlining the technical architecture for a real-time logistics tracking system."
                  documentType="frd"
                />
              </div>
            </TabsContent>
            
            {/* Mockup Examples */}
            <TabsContent value="mockup" className="mt-2">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <ExampleCard 
                  title="Social Media App"
                  category="Social"
                  description="Modern UI/UX mockups for a new social media platform focusing on short-form video content sharing."
                  documentType="mockup"
                />
                <ExampleCard 
                  title="Food Delivery Service"
                  category="Food & Beverage"
                  description="Detailed mockups for a food delivery app with real-time tracking, ratings, and personalized recommendations."
                  documentType="mockup"
                />
                <ExampleCard 
                  title="Fitness Tracker"
                  category="Health & Fitness"
                  description="Clean and intuitive UI mockups for a fitness tracking application with workout plans and progress visualization."
                  documentType="mockup"
                />
                <ExampleCard 
                  title="Learning Management System"
                  category="Education"
                  description="Comprehensive mockups for an online learning platform with course content, assignments, and progress tracking."
                  documentType="mockup"
                />
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-gray-50">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-6">Ready to Create Your Own?</h2>
          <p className="text-lg text-gray-700 mb-8 max-w-2xl mx-auto">
            Start transforming your ideas into detailed documents and beautiful designs with Tekk.ai.
          </p>
          <Link to="/create">
            <Button className="bg-tekk-purple hover:bg-tekk-secondary-purple text-white px-8 py-6 text-lg">
              Create Now
            </Button>
          </Link>
        </div>
      </section>
    </Layout>
  );
};

interface ExampleCardProps {
  title: string;
  category: string;
  description: string;
  documentType: "prd" | "frd" | "mockup";
}

const ExampleCard = ({ title, category, description, documentType }: ExampleCardProps) => {
  // Choose icon based on document type
  const icon = () => {
    switch (documentType) {
      case "prd":
        return <FileText className="h-10 w-10 text-tekk-purple" />;
      case "frd":
        return <LayoutIcon className="h-10 w-10 text-tekk-purple" />;
      case "mockup":
        return <Pencil className="h-10 w-10 text-tekk-purple" />;
    }
  };

  // Choose button text based on document type
  const buttonText = () => {
    switch (documentType) {
      case "prd":
        return "View PRD Example";
      case "frd":
        return "View FRD Example";
      case "mockup":
        return "View Mockup Example";
    }
  };

  return (
    <Card className="h-full flex flex-col hover:shadow-lg transition-shadow">
      <CardContent className="pt-6 flex-grow">
        <div className="flex justify-between items-start mb-4">
          <div className="bg-tekk-soft-purple p-3 rounded-lg">
            {icon()}
          </div>
          <span className="text-sm bg-gray-100 px-3 py-1 rounded-full text-gray-600">
            {category}
          </span>
        </div>
        <h3 className="text-xl font-semibold mb-2">{title}</h3>
        <p className="text-gray-600">{description}</p>
      </CardContent>
      <CardFooter>
        <Button 
          variant="ghost" 
          className="w-full text-tekk-purple hover:bg-tekk-soft-purple hover:text-tekk-purple"
        >
          {buttonText()}
        </Button>
      </CardFooter>
    </Card>
  );
};

export default Examples;
